version: "3.6"
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://username:${PGPASSWORD}@postgres:5432/mydb
    networks:
      - app_network

  postgres:
    image: postgres:13
    ports:
      - "5932:5432" # Expose PostgreSQL on port 5932 to avoid port collision
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
