services:
  # NextJS frontend on port 3000
  frontend:
    build:
      context: . # Adjust path if your frontend is in a subdirectory
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app_network

  # Backend server on port 3001
  backend:
    build:
      context: . # Adjust path if your backend is in a subdirectory
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    depends_on:
      - frontend
    environment:
      DATABASE_URL: postgresql://postgres:${PGPASSWORD}@postgres:5432/warsworld
      PORT: 3001
    networks:
      - app_network

  # PostgreSQL database
  postgres:
    image: postgres:13
    ports:
      - "5932:5432" # You can change this if needed
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: warsworld
    networks:
      - app_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app_network:
    driver: bridge

volumes:
  db_data: