name: Pull Request Checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pr-checks:
    name: Build, Lint, and Prettier
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["18.x"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install deps (with cache)
        run: npm install

      - name: Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ runner.node }}-${{ hashFiles('**/package-lock.yaml') }}-nextjs

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint
